//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.datas.languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.datas.languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easy Save (group 7) is a university project developed by 3rd year computer science students at CESI. The goal of this project is to create a simple and efficient data backup application.
        ///Our team worked hard to develop an application that offers an intuitive and easy-to-use user experience while providing advanced data backup features. We have implemented advanced security mechanisms to ensure the confidentiality and integrity of the backed up data.
        ///
        ///.
        /// </summary>
        internal static string aboutdesc {
            get {
                return ResourceManager.GetString("aboutdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About us.
        /// </summary>
        internal static string AboutMainWindow {
            get {
                return ResourceManager.GetString("AboutMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an option.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please delete save file..
        /// </summary>
        internal static string askdel {
            get {
                return ResourceManager.GetString("askdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software.
        /// </summary>
        internal static string busisoft {
            get {
                return ResourceManager.GetString("busisoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear inputs.
        /// </summary>
        internal static string clearinputsjob {
            get {
                return ResourceManager.GetString("clearinputsjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation date.
        /// </summary>
        internal static string creadate {
            get {
                return ResourceManager.GetString("creadate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of job failed..
        /// </summary>
        internal static string createfail {
            get {
                return ResourceManager.GetString("createfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of job successful..
        /// </summary>
        internal static string createsuccess {
            get {
                return ResourceManager.GetString("createsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable encryption.
        /// </summary>
        internal static string cryptactive {
            get {
                return ResourceManager.GetString("cryptactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptosoft path.
        /// </summary>
        internal static string cryptopath {
            get {
                return ResourceManager.GetString("cryptopath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily logs..
        /// </summary>
        internal static string daylog {
            get {
                return ResourceManager.GetString("daylog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove failed..
        /// </summary>
        internal static string deletefail {
            get {
                return ResourceManager.GetString("deletefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected job.
        /// </summary>
        internal static string deletejob {
            get {
                return ResourceManager.GetString("deletejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose wich save number shall be deleted.
        /// </summary>
        internal static string deletesave {
            get {
                return ResourceManager.GetString("deletesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted..
        /// </summary>
        internal static string deletesucces {
            get {
                return ResourceManager.GetString("deletesucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string diff {
            get {
                return ResourceManager.GetString("diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documentation.
        /// </summary>
        internal static string docu {
            get {
                return ResourceManager.GetString("docu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The documentation is available online and you can access it at any time to get answers to your questions or to discover new features. It is organized in a clear and structured manner so you can easily find the information you need..
        /// </summary>
        internal static string docudesc {
            get {
                return ResourceManager.GetString("docudesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in path..
        /// </summary>
        internal static string errorpath {
            get {
                return ResourceManager.GetString("errorpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all.
        /// </summary>
        internal static string execalljob {
            get {
                return ResourceManager.GetString("execalljob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute.
        /// </summary>
        internal static string execselectedjob {
            get {
                return ResourceManager.GetString("execselectedjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executions.
        /// </summary>
        internal static string ExecutionMainWindow {
            get {
                return ResourceManager.GetString("ExecutionMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch job.
        /// </summary>
        internal static string exesave {
            get {
                return ResourceManager.GetString("exesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File extensions to consider, each extension must be separated by a comma (&quot;*&quot; for all).
        /// </summary>
        internal static string extensionscrypt {
            get {
                return ResourceManager.GetString("extensionscrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language unknow..
        /// </summary>
        internal static string faillang {
            get {
                return ResourceManager.GetString("faillang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files left to copy.
        /// </summary>
        internal static string filleft {
            get {
                return ResourceManager.GetString("filleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory path (From).
        /// </summary>
        internal static string fromdir {
            get {
                return ResourceManager.GetString("fromdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Our support team is always ready to help you solve your problems and answer your questions. If you need help using our application, please feel free to contact us by email or phone..
        /// </summary>
        internal static string helpdesc {
            get {
                return ResourceManager.GetString("helpdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string HelpMainWindow {
            get {
                return ResourceManager.GetString("HelpMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please input a number.
        /// </summary>
        internal static string inputnumber {
            get {
                return ResourceManager.GetString("inputnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job N°.
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        internal static string JobMainWindow {
            get {
                return ResourceManager.GetString("JobMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting  job..
        /// </summary>
        internal static string jobtittle {
            get {
                return ResourceManager.GetString("jobtittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last modification.
        /// </summary>
        internal static string lastmod {
            get {
                return ResourceManager.GetString("lastmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs..
        /// </summary>
        internal static string listlog {
            get {
                return ResourceManager.GetString("listlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of job.
        /// </summary>
        internal static string listsave {
            get {
                return ResourceManager.GetString("listsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à log.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        internal static string LogsMainWindow {
            get {
                return ResourceManager.GetString("LogsMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum Files Size that can be save simulatenously in kO (0 to none):.
        /// </summary>
        internal static string maxfilsiz {
            get {
                return ResourceManager.GetString("maxfilsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is already 5 save job.
        /// </summary>
        internal static string maxsave {
            get {
                return ResourceManager.GetString("maxsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an option (between 1-7).
        /// </summary>
        internal static string menu_0 {
            get {
                return ResourceManager.GetString("menu_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create job..
        /// </summary>
        internal static string menu_1 {
            get {
                return ResourceManager.GetString("menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display job..
        /// </summary>
        internal static string menu_2 {
            get {
                return ResourceManager.GetString("menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job..
        /// </summary>
        internal static string menu_3 {
            get {
                return ResourceManager.GetString("menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start one or more job..
        /// </summary>
        internal static string menu_4 {
            get {
                return ResourceManager.GetString("menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display daily logs..
        /// </summary>
        internal static string menu_5 {
            get {
                return ResourceManager.GetString("menu_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language..
        /// </summary>
        internal static string menu_6 {
            get {
                return ResourceManager.GetString("menu_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close program..
        /// </summary>
        internal static string menu_7 {
            get {
                return ResourceManager.GetString("menu_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New job.
        /// </summary>
        internal static string newjob {
            get {
                return ResourceManager.GetString("newjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No selected file.
        /// </summary>
        internal static string nofile {
            get {
                return ResourceManager.GetString("nofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open documentation.
        /// </summary>
        internal static string opendoc {
            get {
                return ResourceManager.GetString("opendoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority.
        /// </summary>
        internal static string prio {
            get {
                return ResourceManager.GetString("prio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à progress.
        /// </summary>
        internal static string progr {
            get {
                return ResourceManager.GetString("progr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select file to read.
        /// </summary>
        internal static string readwhat {
            get {
                return ResourceManager.GetString("readwhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Job Modifications.
        /// </summary>
        internal static string savejob {
            get {
                return ResourceManager.GetString("savejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name.
        /// </summary>
        internal static string savename {
            get {
                return ResourceManager.GetString("savename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job n°.
        /// </summary>
        internal static string savenum {
            get {
                return ResourceManager.GetString("savenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during the job process....
        /// </summary>
        internal static string saverror {
            get {
                return ResourceManager.GetString("saverror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save state.
        /// </summary>
        internal static string savestate {
            get {
                return ResourceManager.GetString("savestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save successfull..
        /// </summary>
        internal static string savesucc {
            get {
                return ResourceManager.GetString("savesucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save type.
        /// </summary>
        internal static string savetype {
            get {
                return ResourceManager.GetString("savetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select language.
        /// </summary>
        internal static string selectlanguage {
            get {
                return ResourceManager.GetString("selectlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a file.
        /// </summary>
        internal static string selfile {
            get {
                return ResourceManager.GetString("selfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptosoft is a cripting software that uses XOR algorithm. With Cryptosoft you can crypt files to ensure data safety..
        /// </summary>
        internal static string setdesc {
            get {
                return ResourceManager.GetString("setdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set extensions you want to encrypt (put them separated by a space or &quot;*&quot; to encrypt every file).
        /// </summary>
        internal static string setextension {
            get {
                return ResourceManager.GetString("setextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string SettingsMainWindow {
            get {
                return ResourceManager.GetString("SettingsMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of jobs.
        /// </summary>
        internal static string showsave {
            get {
                return ResourceManager.GetString("showsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status of the backup.
        /// </summary>
        internal static string statesave {
            get {
                return ResourceManager.GetString("statesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string stopjob {
            get {
                return ResourceManager.GetString("stopjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory path (To).
        /// </summary>
        internal static string todir {
            get {
                return ResourceManager.GetString("todir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of copied files.
        /// </summary>
        internal static string ttlfilcop {
            get {
                return ResourceManager.GetString("ttlfilcop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total size of copied files.
        /// </summary>
        internal static string ttlfilsiz {
            get {
                return ResourceManager.GetString("ttlfilsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorect input..
        /// </summary>
        internal static string wronginput {
            get {
                return ResourceManager.GetString("wronginput", resourceCulture);
            }
        }
    }
}
