//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.datas.languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class French {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal French() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.datas.languages.French", typeof(French).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easy Save (groupe 7) est un projet universitaire développé par des étudiants en informatique de 3ème année à l&apos;école CESI. L&apos;objectif de ce projet est de créer une application de sauvegarde de données simple et efficace.
        ///Notre équipe a travaillé dur pour développer une application qui offre une expérience utilisateur intuitive et facile à utiliser tout en offrant des fonctionnalités avancées de sauvegarde de données. Nous avons mis en place des mécanismes de sécurité avancés pour garantir la confidentialit [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string aboutdesc {
            get {
                return ResourceManager.GetString("aboutdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        internal static string AboutMainWindow {
            get {
                return ResourceManager.GetString("AboutMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir une action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;en supprimer pour pouvoir en créer de nouveaux..
        /// </summary>
        internal static string askdel {
            get {
                return ResourceManager.GetString("askdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel metier.
        /// </summary>
        internal static string busisoft {
            get {
                return ResourceManager.GetString("busisoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialiser.
        /// </summary>
        internal static string clearinputsjob {
            get {
                return ResourceManager.GetString("clearinputsjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de creation.
        /// </summary>
        internal static string creadate {
            get {
                return ResourceManager.GetString("creadate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création du travaux echouée..
        /// </summary>
        internal static string creatfail {
            get {
                return ResourceManager.GetString("creatfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création du travaux effectuée..
        /// </summary>
        internal static string creatsucc {
            get {
                return ResourceManager.GetString("creatsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activer le chiffrement.
        /// </summary>
        internal static string cryptactive {
            get {
                return ResourceManager.GetString("cryptactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin pour Cryptosoft.
        /// </summary>
        internal static string cryptopath {
            get {
                return ResourceManager.GetString("cryptopath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs journaliers..
        /// </summary>
        internal static string daylog {
            get {
                return ResourceManager.GetString("daylog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression echouée..
        /// </summary>
        internal static string deletefail {
            get {
                return ResourceManager.GetString("deletefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le travail.
        /// </summary>
        internal static string deletejob {
            get {
                return ResourceManager.GetString("deletejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir le travail que vous voulez supprimer..
        /// </summary>
        internal static string deletesave {
            get {
                return ResourceManager.GetString("deletesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression effectuée..
        /// </summary>
        internal static string deletesucces {
            get {
                return ResourceManager.GetString("deletesucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle..
        /// </summary>
        internal static string diff {
            get {
                return ResourceManager.GetString("diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repertoire.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documentation.
        /// </summary>
        internal static string docu {
            get {
                return ResourceManager.GetString("docu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La documentation est consultable en ligne et vous pouvez y accéder à tout moment pour obtenir des réponses à vos questions ou pour découvrir de nouvelles fonctionnalités. Elle est organisée de manière claire et structurée pour vous permettre de trouver facilement les informations dont vous avez besoin..
        /// </summary>
        internal static string docudesc {
            get {
                return ResourceManager.GetString("docudesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur dans la saisie des chemins..
        /// </summary>
        internal static string errorpath {
            get {
                return ResourceManager.GetString("errorpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer tous les travaux.
        /// </summary>
        internal static string execalljob {
            get {
                return ResourceManager.GetString("execalljob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le numéro job à executer. (Entrez 0 pour tous les lancer).
        /// </summary>
        internal static string execsave {
            get {
                return ResourceManager.GetString("execsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer .
        /// </summary>
        internal static string execselectedjob {
            get {
                return ResourceManager.GetString("execselectedjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executions.
        /// </summary>
        internal static string ExecutionMainWindow {
            get {
                return ResourceManager.GetString("ExecutionMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extentions de fichier à prendre en compte, chaque extension doit être séparée par une virgule (&quot;*&quot; pour tous).
        /// </summary>
        internal static string extensionscrypt {
            get {
                return ResourceManager.GetString("extensionscrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue non trouvée.
        /// </summary>
        internal static string faillang {
            get {
                return ResourceManager.GetString("faillang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FIchier restant.
        /// </summary>
        internal static string filleft {
            get {
                return ResourceManager.GetString("filleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du répertoire (Source) :.
        /// </summary>
        internal static string fromdir {
            get {
                return ResourceManager.GetString("fromdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complète..
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notre équipe d&apos;assistance est toujours prête à vous aider à résoudre vos problèmes et répondre à vos questions. Si vous avez besoin d&apos;aide pour utiliser notre application, n&apos;hésitez pas à nous contacter par mail ou par téléphone..
        /// </summary>
        internal static string helpdesc {
            get {
                return ResourceManager.GetString("helpdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        internal static string HelpMainWindow {
            get {
                return ResourceManager.GetString("HelpMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un nombre.
        /// </summary>
        internal static string inputnumber {
            get {
                return ResourceManager.GetString("inputnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux N° .
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux.
        /// </summary>
        internal static string JobMainWindow {
            get {
                return ResourceManager.GetString("JobMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executer un travaux de sauvegarde..
        /// </summary>
        internal static string jobtittle {
            get {
                return ResourceManager.GetString("jobtittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des langues disponibles .
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernieres modification.
        /// </summary>
        internal static string lastmod {
            get {
                return ResourceManager.GetString("lastmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des logs stockées sur le serveur:.
        /// </summary>
        internal static string listlog {
            get {
                return ResourceManager.GetString("listlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des travaux de sauvegarde..
        /// </summary>
        internal static string listsave {
            get {
                return ResourceManager.GetString("listsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string LogsMainWindow {
            get {
                return ResourceManager.GetString("LogsMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille maximale des fichiers qui peuvent etre sauvegarder simultanement en kO (0 pour aucune limite).
        /// </summary>
        internal static string maxfilsiz {
            get {
                return ResourceManager.GetString("maxfilsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il existe déjà 5 travaux de sauvegarde..
        /// </summary>
        internal static string maxsave {
            get {
                return ResourceManager.GetString("maxsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des actions (entre 1 et 7) .
        /// </summary>
        internal static string menu_0 {
            get {
                return ResourceManager.GetString("menu_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travaux de sauvegarde..
        /// </summary>
        internal static string menu_1 {
            get {
                return ResourceManager.GetString("menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les travaux de sauvegarde..
        /// </summary>
        internal static string menu_2 {
            get {
                return ResourceManager.GetString("menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un travaux de sauvegarde..
        /// </summary>
        internal static string menu_3 {
            get {
                return ResourceManager.GetString("menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executer un ou plusieurs travaux..
        /// </summary>
        internal static string menu_4 {
            get {
                return ResourceManager.GetString("menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les logs journaliers..
        /// </summary>
        internal static string menu_5 {
            get {
                return ResourceManager.GetString("menu_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer la langue..
        /// </summary>
        internal static string menu_6 {
            get {
                return ResourceManager.GetString("menu_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter le programme..
        /// </summary>
        internal static string menu_7 {
            get {
                return ResourceManager.GetString("menu_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom .
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau travail.
        /// </summary>
        internal static string newjob {
            get {
                return ResourceManager.GetString("newjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fichier selectionné.
        /// </summary>
        internal static string nofile {
            get {
                return ResourceManager.GetString("nofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir la documentation.
        /// </summary>
        internal static string opendoc {
            get {
                return ResourceManager.GetString("opendoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aperçu.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priorité.
        /// </summary>
        internal static string prio {
            get {
                return ResourceManager.GetString("prio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progres .
        /// </summary>
        internal static string progr {
            get {
                return ResourceManager.GetString("progr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionnez fichier à lire :.
        /// </summary>
        internal static string readwhat {
            get {
                return ResourceManager.GetString("readwhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder les modifications.
        /// </summary>
        internal static string savejob {
            get {
                return ResourceManager.GetString("savejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail de sauvegarde :.
        /// </summary>
        internal static string savename {
            get {
                return ResourceManager.GetString("savename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux n° .
        /// </summary>
        internal static string savenum {
            get {
                return ResourceManager.GetString("savenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du processus de sauvegarde....
        /// </summary>
        internal static string saverror {
            get {
                return ResourceManager.GetString("saverror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat de la sauvegarde.
        /// </summary>
        internal static string savestate {
            get {
                return ResourceManager.GetString("savestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde(s) effectuée(s) avec succès..
        /// </summary>
        internal static string savesucc {
            get {
                return ResourceManager.GetString("savesucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de la sauvegarde .
        /// </summary>
        internal static string savetype {
            get {
                return ResourceManager.GetString("savetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection language .
        /// </summary>
        internal static string selectlanguage {
            get {
                return ResourceManager.GetString("selectlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un fichier.
        /// </summary>
        internal static string selfile {
            get {
                return ResourceManager.GetString("selfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft est un logiciel de cryptage de fichiers qui utilise l&apos;algorithme XOR pour chiffrer les données. Avec CryptoSoft, vous pouvez crypter des fichiers pour protéger leur contenu..
        /// </summary>
        internal static string setdesc {
            get {
                return ResourceManager.GetString("setdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez les extensions que vous voulez chiffrer (rentrez les en les séparant par des espaces ou &quot;*&quot; pour tout chiffrer).
        /// </summary>
        internal static string setextension {
            get {
                return ResourceManager.GetString("setextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parametres.
        /// </summary>
        internal static string SettingsMainWindow {
            get {
                return ResourceManager.GetString("SettingsMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des travaux de sauvegardes .
        /// </summary>
        internal static string showsave {
            get {
                return ResourceManager.GetString("showsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat .
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut de la sauvegarde.
        /// </summary>
        internal static string statesave {
            get {
                return ResourceManager.GetString("statesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arret.
        /// </summary>
        internal static string stopjob {
            get {
                return ResourceManager.GetString("stopjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du répertoire (Destination) .
        /// </summary>
        internal static string todir {
            get {
                return ResourceManager.GetString("todir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre total de fichers.
        /// </summary>
        internal static string ttlfilcop {
            get {
                return ResourceManager.GetString("ttlfilcop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille totale des fichiers.
        /// </summary>
        internal static string ttlfilsiz {
            get {
                return ResourceManager.GetString("ttlfilsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisie incorrecte..
        /// </summary>
        internal static string wronginput {
            get {
                return ResourceManager.GetString("wronginput", resourceCulture);
            }
        }
    }
}
